sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  - chmod +x /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/bower
  - npm -g install npm@^2
  - npm -g install bower
  - npm -g install yarn
  - yarn cache clean

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: 53b93989-0012-4d4f-a673-757958b0a1a8
  app: creche-system
  on: development