sudo: required
language: java
jdk: oraclejdk8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - chmod +x mvnw
  - npm -g install npm@^2
  - npm -g install bower
  - npm -g install yarn
  - yarn cache clean
  - bower install -f

deploy:
  provider: heroku
  api_key:
    secure: 53b93989-0012-4d4f-a673-757958b0a1a8
  app: creche-system
  on: development