sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
before_script:
  - npm -g install npm@^2
  - npm -g install bower
  - npm -g install yarn
  - yarn cache clean
  - bower install -f

script:
  - ./mvnw clean install -B

deploy:
  provider: heroku
  api_key:
    secure: 53b93989-0012-4d4f-a673-757958b0a1a8
  app: creche-system
  on: development