sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: 53b93989-0012-4d4f-a673-757958b0a1a8
  app: creche-system
  on: master